projConfig.toml for paxos_go

[meta]
    version = '0.1.0'

[project]
    name = 'paxos_go'  # distro name
    package = 'paxos_go'  # internal name
    main_lang = 'go'
    version = '0.4.9'
    version_date = '2017-05-17'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2014-2016'
    description = 'a paxos library'
    dev_status = 'pre-alpha'
    license = 'mit'
    relpath = 'go/src/github.com/jddixon/paxos_go'
    state = 'shared'
    url = 'https://jddixon.github.io/paxos_go'

[go]
    cmds=[]
